### ISSUE TITLE
Add slide direction and overlay options

### ISSUE THREAD

**Issue by lawlesscreation** [nomensa/jquery.hide-show#18]
It would be nice to add different slide directions as required e.g.:

```
slideDirection: 'top' // left, bottom, right
```

As well as add an overlay (a little like a lightbox would do) for off-canvas hide-show elements e.g.:

```
overlayEnabled: false // true
```

**Comment by lawlesscreation** [comment]
It might be best to keep the overlay option out of the plugin - instead adding some additional callbacks that trigger on open/close. That way we have more flexibility in the future to do overlays or any other kind of DOM manipulation.

**Comment by anevins12** [comment]
Let's separate out the overlay option in another ticket.

The slide direction enhancement has been completed and a pull request made: https://github.com/nomensa/jquery.hide-show/pull/21

**Comment by lawlesscreation** [comment]
For the slide direction, it will be best to use the open/close callbacks to be added. This will allow you to customise what happens. You could also update the 'speed' to allow 'none' or '0' in which case, the slideDown|Up will ignored.

**Comment by anevins12** [comment]
I've removed the slide direction enhancement and added a callback at the end of the animation

**Comment by anevins12** [comment]
This is ready for Peer Review #21
